version: "3.9"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-c36vZyNgg_sgxZBuT4zt
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ./media:/data
    restart: always
